import { Product } from './types';

export const productDatabase: Product[] = [
  // ═══════════════════════════════════════════
  // OIL CLEANSE
  // ═══════════════════════════════════════════
  {
    id: 'oc-premium-1',
    name: 'Shu Uemura Ultime8 Cleansing Oil',
    brand: 'Shu Uemura',
    category: 'Oil Cleanse',
    reasoning: '',
    ritual: 'Apply 2-3 pumps to dry hands. Massage onto dry face in circular motions for 60 seconds. Emulsify with a splash of water, then rinse.',
    time: '60s',
    state: 'Bone-Dry',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'dry', 'balanced'],
    climates: ['humid', 'arid', 'pollution', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture', 'none'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'oc-budget-1',
    name: 'KOSE Softymo Speedy Cleansing Oil',
    brand: 'KOSE',
    category: 'Oil Cleanse',
    reasoning: '',
    ritual: 'Apply 2-3 pumps to dry hands. Massage onto dry face for 60 seconds, focusing on areas with sunscreen or makeup. Emulsify and rinse.',
    time: '60s',
    state: 'Bone-Dry',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo', 'dry', 'balanced'],
    climates: ['humid', 'arid', 'pollution', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture', 'none'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },

  // ═══════════════════════════════════════════
  // WATER CLEANSE
  // ═══════════════════════════════════════════
  {
    id: 'wc-premium-1',
    name: 'Tatcha The Deep Cleanse',
    brand: 'Tatcha',
    category: 'Water Cleanse',
    reasoning: '',
    ritual: 'Lather a small amount with water between palms. Massage onto damp face for 30 seconds. Rinse thoroughly with lukewarm water.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
  },
  {
    id: 'wc-premium-2',
    name: 'Sulwhasoo Gentle Cleansing Foam',
    brand: 'Sulwhasoo',
    category: 'Water Cleanse',
    reasoning: '',
    ritual: 'Pump a coin-sized amount. Lather gently and massage in upward strokes for 30 seconds. Rinse with cool water.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'wc-budget-1',
    name: 'CeraVe Hydrating Facial Cleanser',
    brand: 'CeraVe',
    category: 'Water Cleanse',
    reasoning: '',
    ritual: 'Apply a small amount to damp skin. Massage gently for 30 seconds without over-foaming. Rinse with lukewarm water.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'wc-budget-2',
    name: 'La Roche-Posay Toleriane Purifying Foaming Cleanser',
    brand: 'La Roche-Posay',
    category: 'Water Cleanse',
    reasoning: '',
    ritual: 'Pump onto wet hands, lather, and apply to damp face for 30 seconds. Rinse thoroughly.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged'],
    ageGroups: ['under25', '25to40', '41to60'],
  },

  // ═══════════════════════════════════════════
  // TONER
  // ═══════════════════════════════════════════
  {
    id: 'tn-premium-1',
    name: 'SK-II Facial Treatment Essence',
    brand: 'SK-II',
    category: 'Toner',
    reasoning: '',
    ritual: 'Pour into palms and press gently into clean, slightly damp skin. Pat until absorbed.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['enlarged', 'texture', 'none'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'tn-premium-2',
    name: 'Laneige Cream Skin Toner & Moisturizer',
    brand: 'Laneige',
    category: 'Toner',
    reasoning: '',
    ritual: 'Soak a cotton pad or pour into palms. Press and pat onto damp skin for deep hydration layering.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'tn-budget-1',
    name: 'Klairs Supple Preparation Unscented Toner',
    brand: 'Dear Klairs',
    category: 'Toner',
    reasoning: '',
    ritual: 'Pour a few drops into palms. Pat gently onto clean, damp face and neck.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced', 'oily'],
    climates: ['arid', 'normal', 'humid'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'tn-budget-2',
    name: 'COSRX AHA/BHA Clarifying Treatment Toner',
    brand: 'COSRX',
    category: 'Toner',
    reasoning: '',
    ritual: 'Apply with cotton pad, sweeping across T-zone and chin. Avoid eye area.',
    time: '15s',
    state: 'Clean',
    isSafetyActive: true,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
  },

  // ═══════════════════════════════════════════
  // ESSENCE
  // ═══════════════════════════════════════════
  {
    id: 'es-premium-1',
    name: 'Sulwhasoo First Care Activating Serum',
    brand: 'Sulwhasoo',
    category: 'Essence',
    reasoning: '',
    ritual: 'Dispense 2-3 drops into palms. Press into damp skin with gentle upward patting motions.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'es-premium-2',
    name: 'Missha Time Revolution The First Treatment Essence RX',
    brand: 'Missha',
    category: 'Essence',
    reasoning: '',
    ritual: 'Apply a generous amount onto palms. Pat into clean, damp skin and allow full absorption.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['enlarged', 'texture', 'none'],
    ageGroups: ['under25', '25to40', '41to60'],
  },
  {
    id: 'es-budget-1',
    name: 'COSRX Advanced Snail 96 Mucin Power Essence',
    brand: 'COSRX',
    category: 'Essence',
    reasoning: '',
    ritual: 'Scoop a small amount with the spatula. Pat onto damp skin, layering for extra hydration if desired.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced', 'oily'],
    climates: ['arid', 'normal', 'humid', 'pollution'],
    repairTargets: ['redness', 'pih', 'clean'],
    poreTargets: ['none', 'texture', 'enlarged'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },

  // ═══════════════════════════════════════════
  // SERUM
  // ═══════════════════════════════════════════
  {
    id: 'sr-premium-1',
    name: 'Drunk Elephant T.L.C. Framboos Glycolic Night Serum',
    brand: 'Drunk Elephant',
    category: 'Serum',
    reasoning: '',
    ritual: 'Apply 2-3 pumps to clean, dry face at night. Wait 3 minutes before next step. Do not mix with Vitamin C.',
    time: 'Wait 3m',
    state: 'Bone-Dry',
    isSafetyActive: true,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['25to40', '41to60'],
  },
  {
    id: 'sr-premium-2',
    name: 'Estée Lauder Advanced Night Repair Serum',
    brand: 'Estée Lauder',
    category: 'Serum',
    reasoning: '',
    ritual: 'Apply 1-2 drops to clean face and neck. Pat gently until absorbed.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'sr-premium-3',
    name: 'Skinceuticals C E Ferulic',
    brand: 'Skinceuticals',
    category: 'Serum',
    reasoning: '',
    ritual: 'Apply 4-5 drops to dry face in the morning. Wait 2 minutes before moisturizer.',
    time: 'Wait 2m',
    state: 'Bone-Dry',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced', 'dry'],
    climates: ['pollution', 'normal', 'arid'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['none', 'texture', 'enlarged'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'sr-budget-1',
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'Serum',
    reasoning: '',
    ritual: 'Apply a few drops to clean, slightly damp skin. Pat gently. Can be used morning and night.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
  },
  {
    id: 'sr-budget-2',
    name: 'The Ordinary Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    category: 'Serum',
    reasoning: '',
    ritual: 'Apply a few drops to clean skin morning and night. Follow with moisturizer.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo', 'dry', 'balanced'],
    climates: ['humid', 'arid', 'pollution', 'normal'],
    repairTargets: ['pih'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'sr-budget-3',
    name: 'Paula\'s Choice 2% BHA Liquid Exfoliant',
    brand: 'Paula\'s Choice',
    category: 'Serum',
    reasoning: '',
    ritual: 'After cleansing, apply with cotton pad to face. Wait 3 minutes before next step. Start with every other night.',
    time: 'Wait 3m',
    state: 'Clean',
    isSafetyActive: true,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
  },

  // ═══════════════════════════════════════════
  // TREAT
  // ═══════════════════════════════════════════
  {
    id: 'tr-premium-1',
    name: 'La Mer The Eye Concentrate',
    brand: 'La Mer',
    category: 'Treat',
    reasoning: '',
    ritual: 'Using ring finger, dab a small amount around the orbital bone. Pat gently, never drag.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['none'],
    ageGroups: ['41to60', 'over60'],
  },
  {
    id: 'tr-premium-2',
    name: 'Sunday Riley Good Genes All-In-One Lactic Acid Treatment',
    brand: 'Sunday Riley',
    category: 'Treat',
    reasoning: '',
    ritual: 'Apply a thin layer to face at night after serum. May tingle slightly. Wait 2 minutes before moisturizer.',
    time: 'Wait 2m',
    state: 'Clean',
    isSafetyActive: true,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['25to40', '41to60'],
  },
  {
    id: 'tr-budget-1',
    name: 'The Ordinary Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    category: 'Treat',
    reasoning: '',
    ritual: 'Apply a small amount to areas of concern after serum. Pat gently.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'redness'],
    poreTargets: ['blackheads', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
  },
  {
    id: 'tr-budget-2',
    name: 'CeraVe Eye Repair Cream',
    brand: 'CeraVe',
    category: 'Treat',
    reasoning: '',
    ritual: 'Dab a tiny amount under each eye with ring finger. Pat gently along orbital bone.',
    time: '10s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced', 'oily'],
    climates: ['arid', 'normal', 'humid', 'pollution'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['none'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },

  // ═══════════════════════════════════════════
  // MOISTURIZE
  // ═══════════════════════════════════════════
  {
    id: 'mo-premium-1',
    name: 'La Mer Crème de la Mer',
    brand: 'La Mer',
    category: 'Moisturize',
    reasoning: '',
    ritual: 'Warm a small amount between fingertips. Press into skin with gentle patting motions. Layer more on dry areas.',
    time: '30s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['41to60', 'over60'],
  },
  {
    id: 'mo-premium-2',
    name: 'Tatcha The Dewy Skin Cream',
    brand: 'Tatcha',
    category: 'Moisturize',
    reasoning: '',
    ritual: 'Apply a pearl-sized amount to face and neck. Press and smooth in upward motions.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'pih', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'mo-premium-3',
    name: 'Amorepacific Moisture Bound Hydration Gel',
    brand: 'Amorepacific',
    category: 'Moisturize',
    reasoning: '',
    ritual: 'Smooth a thin layer over face. The gel texture absorbs quickly without residue.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['clean', 'pih'],
    poreTargets: ['enlarged', 'blackheads', 'none'],
    ageGroups: ['under25', '25to40', '41to60'],
  },
  {
    id: 'mo-budget-1',
    name: 'CeraVe Moisturizing Cream',
    brand: 'CeraVe',
    category: 'Moisturize',
    reasoning: '',
    ritual: 'Apply generously to face and neck. Massage in circular motions until absorbed.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'mo-budget-2',
    name: 'Neutrogena Hydro Boost Water Gel',
    brand: 'Neutrogena',
    category: 'Moisturize',
    reasoning: '',
    ritual: 'Smooth a thin layer over face. Lightweight gel absorbs rapidly.',
    time: '15s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['clean', 'pih'],
    poreTargets: ['enlarged', 'blackheads', 'none'],
    ageGroups: ['under25', '25to40', '41to60'],
  },

  // ═══════════════════════════════════════════
  // SPF
  // ═══════════════════════════════════════════
  {
    id: 'spf-premium-1',
    name: 'Supergoop! Unseen Sunscreen SPF 40',
    brand: 'Supergoop!',
    category: 'SPF',
    reasoning: '',
    ritual: 'Apply a generous amount as the final step of your morning routine. Reapply every 2 hours when exposed to sun.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture', 'none'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },
  {
    id: 'spf-premium-2',
    name: 'Sulwhasoo UV Wise Brightening Multi Protector',
    brand: 'Sulwhasoo',
    category: 'SPF',
    reasoning: '',
    ritual: 'Apply evenly to face as last skincare step. Provides brightening benefits alongside sun protection.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
  },
  {
    id: 'spf-budget-1',
    name: 'Beauty of Joseon Relief Sun SPF 50+',
    brand: 'Beauty of Joseon',
    category: 'SPF',
    reasoning: '',
    ritual: 'Apply generously as the final step. The rice and probiotics formula doubles as skincare. Reapply every 2 hours.',
    time: '20s',
    state: 'Damp',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo', 'dry', 'balanced'],
    climates: ['humid', 'arid', 'pollution', 'normal'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture', 'none'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
  },

  // ═══════════════════════════════════════════
  // MASK (Wildcards)
  // ═══════════════════════════════════════════
  {
    id: 'mk-premium-1',
    name: 'Tatcha Violet-C Radiance Mask',
    brand: 'Tatcha',
    category: 'Mask',
    reasoning: '',
    ritual: 'Apply a thick, even layer to clean skin. Leave on for 15-20 minutes. Rinse with lukewarm water and follow with toner.',
    time: '15-20m',
    state: 'Clean',
    isSafetyActive: true,
    tier: 'premium',
    skinTypes: ['oily', 'combo', 'balanced'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['pih', 'clean'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['25to40', '41to60'],
    isWildcard: true,
  },
  {
    id: 'mk-premium-2',
    name: 'Sulwhasoo Overnight Vitalizing Mask',
    brand: 'Sulwhasoo',
    category: 'Mask',
    reasoning: '',
    ritual: 'Apply a generous layer as the last step of your night routine. Leave overnight. Rinse in the morning.',
    time: 'Overnight',
    state: 'Clean',
    isSafetyActive: false,
    tier: 'premium',
    skinTypes: ['dry', 'combo', 'balanced'],
    climates: ['arid', 'normal'],
    repairTargets: ['redness', 'clean'],
    poreTargets: ['none', 'texture'],
    ageGroups: ['25to40', '41to60', 'over60'],
    isWildcard: true,
  },
  {
    id: 'mk-budget-1',
    name: 'Innisfree Super Volcanic Pore Clay Mask',
    brand: 'Innisfree',
    category: 'Mask',
    reasoning: '',
    ritual: 'Apply an even layer to clean, dry face. Avoid eye and lip area. Leave 10-15 minutes until dry. Rinse with lukewarm water.',
    time: '10-15m',
    state: 'Clean',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['clean', 'pih'],
    poreTargets: ['blackheads', 'enlarged', 'texture'],
    ageGroups: ['under25', '25to40', '41to60'],
    isWildcard: true,
  },
  {
    id: 'mk-budget-2',
    name: 'I\'m From Rice Toner (as a Toner Mask)',
    brand: "I'm From",
    category: 'Mask',
    reasoning: '',
    ritual: 'Soak cotton pads with toner and place on cheeks, forehead, and chin. Leave for 5-10 minutes for a brightening boost.',
    time: '5-10m',
    state: 'Clean',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['dry', 'combo', 'balanced', 'oily'],
    climates: ['arid', 'normal', 'humid', 'pollution'],
    repairTargets: ['pih', 'redness', 'clean'],
    poreTargets: ['texture', 'none', 'blackheads', 'enlarged'],
    ageGroups: ['under25', '25to40', '41to60', 'over60'],
    isWildcard: true,
  },
  {
    id: 'mk-budget-3',
    name: 'Aztec Secret Indian Healing Clay',
    brand: 'Aztec Secret',
    category: 'Mask',
    reasoning: '',
    ritual: 'Mix equal parts clay powder and apple cider vinegar. Apply to clean face, avoiding eyes. Leave 10-15 minutes. Rinse thoroughly.',
    time: '10-15m',
    state: 'Clean',
    isSafetyActive: false,
    tier: 'budget',
    skinTypes: ['oily', 'combo'],
    climates: ['humid', 'pollution', 'normal'],
    repairTargets: ['clean'],
    poreTargets: ['blackheads', 'enlarged'],
    ageGroups: ['under25', '25to40'],
    isWildcard: true,
  },
];
